### PR TITLE
Added typings

### PR DESCRIPTION
**Pull request by Lexedia**
I just added typings. All the documentation come from your README.

### CODE REVIEW

**Review by Xelzs — APPROVED** [review]
LGTM, thanks for the contribution 👍

**Comment by Lexedia** [comment]
By the way, I just thought of this, but I made a small mistake, I forgot to add `"types": "./index.d.ts",` in the package.json. Could you fix that? Sorry about this mistake 😅

**Comment by Xelzs** [comment]
> By the way, I just thought of this, but I made a small mistake, I forgot to add `"types": "./index.d.ts",` in the package.json. Could you fix that? Sorry about this mistake sweat_smile

Yes, I already saw that before new release, and it was fixed 😉

**Comment by Lexedia** [comment]
> 
> 
> > By the way, I just thought of this, but I made a small mistake, I forgot to add `"types": "./index.d.ts",` in the package.json. Could you fix that? Sorry about this mistake sweat_smile
> 
> Yes, I already saw that before new release, and it was fixed 😉

Nice, thanks a lot 😄

**Pull request merged**
